### ISSUE TITLE
Somatek Biomedical Biodome city not replacing academy

### ISSUE THREAD

**Issue by ZaboTheGreat** [carriontrooper/Alpha-Frontier#24]
I was playing the game as somatek and saw that it doesn't say how to get Biodome city. I decided to see into github and saw that on TileImprovements.json it says Biodome City replaces academy. I made a great scientist, and it built an academy instead of biodome city. 
If you can't get great scientist to make something other than academy, give somatek their own great scientist that makes biodome city.

**Comment by carriontrooper** [comment]
huh, that's strange, this might be a vanilla issue too. In the meantime I'll make the GS replacement - hope it works.

**Comment by carriontrooper** [comment]
just took it up with vanilla UnCiv, seems like this was intended behavior so the replacement GS now sticks
