### ISSUE TITLE
Citadel doesn't change tiles

### ISSUE THREAD

**Issue by r4ffz4hn** [carriontrooper/Alpha-Frontier#26]
Building a citadel seems not to change land ownership.
![Screenshot_20220517-160525_UnCiv](https://user-images.githubusercontent.com/105693653/168726665-0d2d8950-8cc2-4ba3-b301-a80f14b25cf6.jpg)
![Screenshot_20220517-160530_UnCiv](https://user-images.githubusercontent.com/105693653/168726691-878a041c-0a30-46b3-96d4-b1e44f2a1d5c.jpg)

**Comment by carriontrooper** [comment]
Yeah, that's a bug with vanilla too iirc. Latest update and everything?

**Comment by carriontrooper** [comment]
Oh, alright, I see they un-hardcoded the citadel tile bomb. Should be fixed now.
