### ISSUE TITLE
Espirit de Corps applied when next to enemy melee

### ISSUE THREAD

**Issue by Zoogzin** [carriontrooper/Alpha-Frontier#29]
Dunno if intentional but im getting the melee buff when next to enemy melee units
![Screenshot_20220605-125423_UnCiv](https://user-images.githubusercontent.com/93752076/172063827-051cb675-05a6-4543-8eb4-31a1c2881988.jpg)

**Comment by carriontrooper** [comment]
That's a bug in vanilla too, I think they just fixed it in 4.1.7.
