### ISSUE TITLE
Neo-philosophy does not adjust science value. Playing as skye robotics.

### ISSUE THREAD

**Issue by Zoogzin** [carriontrooper/Alpha-Frontier#30]
So far only played as sky robotics, always with religion turned off, and this is the first time i've tried neo-philosophy. Noticed my science output did not budge. Maybe it's because skye robotics already has a +1 science from every svience building? Otherwise, maybe because religion is off? Unsure if the faith buff is working or not.
![Screenshot_20220606-011113_UnCiv](https://user-images.githubusercontent.com/93752076/172105924-1ae7cc59-8224-46a8-afa6-2114000d1e75.jpg)

**Comment by carriontrooper** [comment]
Hmm, needs more testing:
-try looking at the stats again the turn after getting neo-philosophy
-try neo-philosophy with other civs
-try with religion on

**Comment by Zoogzin** [comment]
Played as somatek with religion on, neither the faith nor science buff applied, even on the following turn.
![Screenshot_20220612-225509_UnCiv](https://user-images.githubusercontent.com/93752076/173277158-d1c06993-8293-4fea-b68a-caeed05449b6.jpg)
![Screenshot_20220612-225610_UnCiv](https://user-images.githubusercontent.com/93752076/173277249-a7da680b-3fe4-48be-bb0b-c6b3e0afff6b.jpg)

**Comment by carriontrooper** [comment]
holy shit that was a doozy, somehow the policies file had a lot of 'from from's, this might be what broke the unique. try again now.

**Comment by Zoogzin** [comment]
Sounds like it was hard to sort through, yeah. Science buff now applies, both with somatek and after accounting for sky robotics. *But* the religion buff isn't applying.

**Comment by carriontrooper** [comment]
hmm, perhaps it wasn't [Religious] but [Faith] instead? Updated it, check how it goes now.

**Comment by Zoogzin** [comment]
That did it, it works! Thanks for all your help!
