### ISSUE TITLE
Trade Port Not Functioning Properly

### ISSUE THREAD

**Issue by TheEXAM** [carriontrooper/Alpha-Frontier#37]
Trade routes don't connect over water.

![Screenshot_20220620-123802_UnCiv](https://user-images.githubusercontent.com/61744611/174526681-15c06d96-d12c-42da-9c12-897a99374d4e.jpg)
![Screenshot_20220620-123813_UnCiv](https://user-images.githubusercontent.com/61744611/174526698-a3faa624-369a-4dac-a775-ca01c64431e3.jpg)
![Screenshot_20220620-123831_UnCiv](https://user-images.githubusercontent.com/61744611/174526704-94051431-a3e0-48f0-b97b-641e5318d72f.jpg)
![Screenshot_20220620-123844_UnCiv](https://user-images.githubusercontent.com/61744611/174526710-de360d0c-dc30-4f39-bf41-d9eee722526b.jpg)

As you can see, these cities have trade ports, but are not connected to a trade route. I tested to see if this is a vanilla unciv problem, but vanilla works fine, so the problem likely lies in the mod.

**Comment by TheEXAM** [comment]
Yes, both cases have capitals with trade ports.

I first noticed this issue when I started a new game as Xenoidid Empire. When I found it, I first loaded a save using vanilla playset; the regular Harbors still worked properly. I then loaded an older save as Free Waverunners, and confirmed that the issue only shows in the mod.

I am sure that the Waverunners save had functioning Trade Ports before I saved the game, so it is possible that some recent update - though I'm not sure whether in the mod or the game itself - messed up something in the code.

**Comment by carriontrooper** [comment]
I think it might be the unciv game, I haven't touched the code part of the game for the Trade Port in a very long while. Can confirm that it also broke in my game - used Waverunners, created another city in the same coast, both capital and city has Trade Port - and nothing.

**Comment by carriontrooper** [comment]
![Screenshot_20220621-172219_UnCiv](https://user-images.githubusercontent.com/78248399/174778331-ab24cb71-2716-4bf3-a2da-8dd88a1a333c.jpg)
![Screenshot_20220621-172242_UnCiv](https://user-images.githubusercontent.com/78248399/174778349-91a024ee-3d57-4dc1-b759-577b123db8ed.jpg)
![Screenshot_20220621-172251_UnCiv](https://user-images.githubusercontent.com/78248399/174778352-3cedd6e6-41cf-45d8-b095-11c913bc883e.jpg)
Adding screenshots from my game for confirmation

**Comment by OptimizedForDensity** [comment]
This bug should be fixed in an upcoming update https://github.com/yairm210/Unciv/pull/7254

**Comment by carriontrooper** [comment]
Seems like vanilla already handled it, let's check with AF.

**Comment by TheEXAM** [comment]
Issue has been fixed after the recent update (4.1.16). Both aforementioned saves now have Trade Ports that connect trade routes over water, thereby making them function as intended. No other issues seem to have come up.
