### ISSUE TITLE
Missing mod file?

### ISSUE THREAD

**Issue by TheEXAM** [carriontrooper/Alpha-Frontier#41]
Somehow, when I updated/reinstalled the mod, it now doesn't appear in the downloaded mod list. I also tried reinstalling the game and then tried to load an Alpha Frontier save - the save couldn't find the mod.

I don't know what exactly happened to have caused this, but so far only the Alpha Frontier mod is experiencing this issue. Below are some screenshots of what I mean.

![Screenshot_20220717-032423_UnCiv](https://user-images.githubusercontent.com/61744611/179369485-26285cc8-f82e-4b5c-a359-4c24b5291703.jpg)
![Screenshot_20220717-032610httuse.githubusercontent.com/61744611/179369486-bc54c768-2a0-4889-b911-5b8258f3837f.jpg)

**Comment by TheEXAM** [comment]
Oops, second screenshot didn't load properly. Here it is:

![Screenshot_20220717-032610_UnCiv](https://user-images.githubusercontent.com/61744611/179369712-f49c5c6f-eb1c-4a35-90bb-4d8c4935a123.jpg)

**Comment by TheEXAM** [comment]
Issue kind of fixed itself. I waited some hours then I tried to redownload the mod; it worked and the save loaded without issue.

It was pretty strange, so I thought it was worth opening this issue, but I'll close it now anyways since it seems fixed.

**Comment by carriontrooper** [comment]
Yeah, it was a missing end bracket, fixed it real quick.
