### ISSUE TITLE
Troublesome "Unique"s

### ISSUE THREAD

**Issue by Unkind98** [carriontrooper/Alpha-Frontier#42]
Dear, @carriontrooper. I am here to report some issues I found after deep research and testing regarding some uniques that have trouble.
1. The conditional unique `<with [amount] to [amount] neighboring [tileFilter] tiles>` (also:  `<with [amount] to [amount] neighboring [tileFilter] [tileFilter] tiles>`) seems not work for TileResoureces uniques. You can check it by using "partial generation editor" in Map Editor. The tested result is that the water (esp. ocean) resources will spawn in an unexpected location (far away from specific related terrains).
![res-distrib-not-legit](https://github.com/Unkind98/Unkind98-Alpha-Frontier-Submod/blob/messages/res-distrib-not-legit.png?raw=true)

2. The parameter for "[stat]" of the conditional unique `May buy [baseUnitFilter] units for [amount] [stat] [cityFilter] at an increasing price ([amount])` cannot be "Gold". If it is it, then, instead of using the expected amount of "[amount]", it will use the cost of "[baseUnitFilter]" as if you purchase it with gold. Also, the expected increasing amount is not working too. For example, The cost amount of an unbuildable unit "Influencer" is 0. And the policy "Influence Completed" that has the unique "May buy [Great Influencer] units for [500] [Gold] [in all cities] at an increasing price ([250])" has been achieved. Now, if you want to buy "Great Influencer" It would cost 0 Gold (modified depending on the game speed) and the price never increases as if you purchase it normally (assuming that the unit is buildable and purchasable). In the short term, the given unique does not work.
![free-great-influencer](https://github.com/Unkind98/Unkind98-Alpha-Frontier-Submod/blob/messages/free-great-influencer.png?raw=true)

That is it for now, and I will add more later.

**Comment by carriontrooper** [comment]
Hmm, thanks for the heads-up - might want to take this up to Unciv issues too.

The resources - afraid there isn't anything I can do on this end, this is a quirk with map generation.

Gold purchase - might be sidestepped, changed it from gold to culture (do tell me if this works or not)

**Comment by Unkind98** [comment]
Aku punya ide gini sih, masih tak coba:
1. Buat terrain baru ("Offshore" misalnya) lalu dibuat unique untuk ocean 'Becomes [Offshore] when adjacent to [Coast]'. Terus, resource-resource yang bermasalah ini parameter '"terrainsCanBeFoundOn"' nya diganti ke offshore dan unique-unique nya disetting ulang lagi lah pokoknya.
2. Kalau parameternya "Culture" nggak akan ada masalah, karena ada contohnya di vanilla.

_PS: yang nomer satu masih aku uji coba, nanti kalau ada perkembangan tak kabari._
_PSS: pake bahasa Indo dulu bre. Ngantuk, malem-malem aku nulis ini sambil donlot anime. Nanti kalau yang nomer satu ada perkembangan baru tak translate ke Inggris biar yg laen pada paham._

**Comment by Unkind98** [comment]
Dear @carriontrooper, this is my advice regarding the issues:
#### Issue 1
Steps:
1. Make a new terrain (I named it "Offshore"). And give "Ocean" a unique `Becomes [Offshore] when adjacent to [Coast]`.
[Example](https://github.com/Unkind98/Unkind98-Alpha-Frontier-Submod/blob/main/jsons/Terrains.json)
2. Make the troublesome resources occur on "Offshore" instead of "Ocean". (also erase the conditional parameter `<with [amount] to [amount] neighboring [tileFilter] tiles>` that exists)
[Example](https://github.com/Unkind98/Unkind98-Alpha-Frontier-Submod/blob/main/jsons/TileResources.json)
3. Boom, problem solved :)

#### Issue 2
If you set the parameter as "Faith" it will work. Problems only occur if you set it other than "Faith". "Culture" and "Science" will work, but it is not recommended. Because we tend to achieve many Techs and Policies as fast as possible.

That is for now, salam Indomie Seleraku.

**Comment by carriontrooper** [comment]
Hmm, maybe inestead of terrain, make Offshore a terrain feature?

Mantabz gan

**Comment by Unkind98** [comment]
That is what just I did in the example I gave you.
[This one](https://github.com/Unkind98/Unkind98-Alpha-Frontier-Submod/blob/main/jsons/Terrains.json)
