### ISSUE TITLE
Map terrain now uses default textures

### ISSUE THREAD

**Issue by Zoogzin** [carriontrooper/Alpha-Frontier#44]
Mod started using the new unciv default map textures maybe a week or two ago, i assume when unciv updated. Good luck! Loving how far the mod has come so far!

![Screenshot_20220809-222055_UnCiv](https://user-images.githubusercontent.com/93752076/183805791-a5413f1d-7a36-418c-b222-9aabb28466f9.jpg)

**Comment by carriontrooper** [comment]
Huh, works in mine - try switching it to FantasyHex. The default used to be FantasyHex but now it's Hexarealm.

**Comment by Zoogzin** [comment]
Works, thanks!
