### ISSUE TITLE
AI doesn't know how to use Constructors on water improvements

### ISSUE THREAD

**Issue by SpacedOutChicken** [carriontrooper/Alpha-Frontier#47]
The AI doesn't know what to do with the dual-purpose Constructor units. It only sets them to work on Land improvements without ever sending them to improve Water resources.

To fix this, I propose removing the "May create improvements on water resources" unique from the Constructor and adding it to a new unit.

**Comment by carriontrooper** [comment]
Oof, this is supposed to be a defining feature. Then vanilla AI can't use Samurais to make fishing boats as well?

**Comment by SpacedOutChicken** [comment]
Possibly not. The AI just isn't smart enough to take advantage of that
feature.

**Comment by DeraiDeJust** [comment]
i already discovered aquaculture but still cannot build improvement on water tiles with constructor, does anyone know why?

**Comment by carriontrooper** [comment]
Whoops, might be because I fiddled with the Constructor for a test. Try it again now, should be back.

**Comment by SpacedOutChicken** [comment]
The AI seems to be smart enough to use the Constructor properly now, so I'm closing this issue.
