### ISSUE TITLE
Missing?

### ISSUE THREAD

**Issue by Alucard0Reborn** [carriontrooper/Alpha-Frontier#49]
So I literally deleted everything by clearing my storage, which I really didn't want to do as I had like a ton of mods installed, and redownloaded Alpha Frontier, and it does not show in the mod list anywhere and is not selectable, and in the mod error page, it shows this. V 
![Screenshot_20221123-003431](https://user-images.githubusercontent.com/38371515/203501917-6fe429ff-2018-4caf-ad6f-f25afeaa6137.png)

**Comment by Alucard0Reborn** [comment]
It was in my list before I updated it. So I'm guessing the recent update borked it somehow?

**Comment by RealBamboolord** [comment]
Because your game is in older version, it cannot use the new City State Types

**Comment by Alucard0Reborn** [comment]
Ugh, I just checked and there was an update. Which is weird cause I went to
check for all my updates and UnCiv wasn't in the list of needing one last
night. I guess the PC version gets the update first and then Android the
next day?

**Comment by carriontrooper** [comment]
Yeah, that one was because of a broken thing that got fixed after. Closing, unless it happens again.
