### ISSUE TITLE
Hovercrafts can't attack on water 

### ISSUE THREAD

**Issue by draco305** [carriontrooper/Alpha-Frontier#50]
As the hovercrafts have access to boarding party promotions, I assume that they should be able to attack water units.

This is not possible from embarked and from neighbor land neither.

I remember that there was a change in vanilla unciv at some point that could have caused this

**Comment by RealBamboolord** [comment]
Seems like it's missing the "Can attack while embarked" unique

**Comment by carriontrooper** [comment]
That's weird, the Hover unitType already has "May attack when embarked"... I'm going to put that unique in Light Hovercraft, please test if it works.

**Comment by carriontrooper** [comment]
Fixed already, closing now.
