### ISSUE TITLE
Proposal: make Biodome City accessible to all civilizations (when given a Great Geneticist)

### ISSUE THREAD

**Issue by SpacedOutChicken** [carriontrooper/Alpha-Frontier#56]
Right now, Great Geneticist units can only build a Biodome City when they're owned by Somatek Biomedical. Most of the time, this isn't an issue, but when a city-state gives you a Great Geneticist as a gift, they're unable to build their special improvement, which seems like a shame to me. If you are so inclined, there is an easy fix: remove the `"uniqueTo": "Somatek Biomedical"` line from the improvement file. This way, any civilization that is given a Great Geneticist as a gift will be able to build it. It will still normally be only accessible to Somatek, because Somatek is the only civilization that can generate Great Geneticist units naturally.

**Comment by carriontrooper** [comment]
Hmmm, you do have a point, lemme make the edit
