### ISSUE TITLE
No Textures

### ISSUE THREAD

**Issue by BillBillBi** [carriontrooper/Alpha-Frontier#6]
Textures for terrain and nation emblems generate as needed. Textures for units, natural wonders, buildings and techs do not.
Unciv Version 4.0.1

**Comment by HaneulCheong** [comment]
Probably because `game.atlas` and all related files are outdated and thus should be updated.

**Comment by carriontrooper** [comment]
Yeah, those are still in progress work. Will close this bug report once they're all finished.

**Comment by Rivirt** [comment]
Still working on it?

**Comment by carriontrooper** [comment]
Yeah, slowing down a bit atm because of commissions, but it's still being worked on

**Comment by carriontrooper** [comment]
Progress report: only the techs, buildings and promotions left.

**Comment by Rivirt** [comment]
Still working on it?

**Comment by carriontrooper** [comment]
Finally done with the icons, I'm going to mark this as completed.
