### ISSUE TITLE
Unable to upgrade units

### ISSUE THREAD

**Issue by Zoogzin** [carriontrooper/Alpha-Frontier#60]
Thanks for continuing to support this mod! 

Images showing the rover upgrade option missing are provided below as an example, but this also happened during the previous build of this mod for the upgrade from scout mecha to combat mecha. 

I recently played other mods, and upgrades worked for those playthroughs, so i wonder if this is a mod-specific issue. I can double-check by trying those mods again if you'd like.

Let me know if you would like further info, thanks again!

![Screenshot_20230927_215850_Unciv](https://github.com/carriontrooper/Alpha-Frontier/assets/93752076/9ac8f370-d526-4ddb-8cbb-c53f1b3f9803)

![Screenshot_20230927_215901_Unciv](https://github.com/carriontrooper/Alpha-Frontier/assets/93752076/29506d87-50a3-4128-8305-0ca7be54033c)

**Comment by carriontrooper** [comment]
Hmm, strange. I'll have to test this on my phone and desktop.

**Comment by Dark0-04** [comment]
This bug seems to affect all units in this mod that require a building.

**Comment by carriontrooper** [comment]
Fixed via vanilla
