### ISSUE TITLE
mod changes the icon for display in settings

### ISSUE THREAD

**Issue by somesi** [carriontrooper/Alpha-Frontier#61]
hi
For some reason when i use this mod the display icon in settings becomes a different icon. Sorry I know its a minor issue but I was curious to find out why it happened.
screenshot: https://ibb.co/RPsgWng (the eye next to display is different then the default one)

**Comment by carriontrooper** [comment]
Yeah, the display icon uses Sentry icon iirc, and Alpha Frontier has a different pic. It's just a visual quirk tho.
