### ISSUE TITLE
Jeager engineering Mechbay

### ISSUE THREAD

**Issue by KaiserFoxian** [carriontrooper/Alpha-Frontier#64]
Jaeger special buliding, Mechbay, gives bonus to built Mechas and Armored. It repleces Mechanaized Units Facility, and _loses the ability to make Mech or Armored_.

**Comment by RealBamboolord** [comment]
That sounds like a base game bug

**Comment by carriontrooper** [comment]
That's just flavor text unique tho - in any case, added it in.
