### ISSUE TITLE
Visionary cannot spread religion

### ISSUE THREAD

**Issue by Renxingdong** [carriontrooper/Alpha-Frontier#67]
![Screenshot_2023-12-25-14-56-38-52_5b83b50424e447777d9855d9701553df](https://github.com/carriontrooper/Alpha-Frontier/assets/6070787/4fec6427-a042-4d6a-a50e-542d5de49c87)

There's no spread religion button

**Comment by carriontrooper** [comment]
Weird... nothing in View More?

**Comment by Renxingdong** [comment]
Nevermind... I upgraded to 4.9.10-patch1 and it worked
