### ISSUE TITLE
City Tile issue.

### ISSUE THREAD

**Issue by KV1T34** [carriontrooper/Alpha-Frontier#80]
City tile not showing correctly.

![Screenshot_20240605_123827_Unciv](https://github.com/carriontrooper/Alpha-Frontier/assets/171823461/dfd21b8b-1101-4eeb-90c1-2bd96a84c825)

Progressing to new ages didnt fix it.

![Screenshot_20240607_072222_Unciv](https://github.com/carriontrooper/Alpha-Frontier/assets/171823461/4320d663-91c7-420a-89b8-6195c965e353)

**Comment by hackedpassword** [comment]
Wrong TileSet. Should be FantasyHex. Change that in Display options.

**Comment by KV1T34** [comment]
Wow, I'm stupid, I only had FantasyHex turned on for units. Thanks dev. Great mod, me like it.
